name: PVS-Studio Static Analysis

on: workflow_dispatch

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.2

      - name: Set Up .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore Bank/Bank.sln

      - name: Build
        run: dotnet build Bank/Bank.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test Bank.Bank.sln --configuration Release --no-build --verbosity normal

  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6.0.2
    
      - name: Install PVS-Studio
        run: |
          wget -q -O - https://wcdn.pvs-studio.com/etc/pubkey.txt | sudo apt-key add -
          sudo wget -O /etc/apt/sources.list.d/viva64.list https://wcdn.pvs-studio.com/etc/viva64.list
          sudo apt-get update
          sudo apt-get install pvs-studio-dotnet

      - name: Set PVS-Studio License
        run: pvs-studio-analyzer credentials ${{secrets.PVS_NAME}} ${{secrets.PVS_KEY}}

      - name: Restore Dependencies
        run: dotnet restore Bank/Bank.sln

      - name: Build
        run: dotnet build Bank/Bank.sln --configuration release --no-restore

      - name: Run PVS-Studio Analysis
        run: |
          set +e
          pvs-studio-dotnet -t Bank/Bank.sln -c Release -o BankLog.json
          EXIT_CODE=$?
          echo "PVS Exit Code: $EXIT_CODE"
          if [ $EXIT_CODE -ne 0 ] && [ $EXIT_CODE -ne 8 ]; then
            exit $EXIT_CODE
          fi
      
      - name: Convert Report to Readable Format
        run: |
          plog-converter -t html -o pvs-report.html BankLog.json

      - name: Artifact PVS Report
        uses: actions/upload-artifact@v5.0.0
        if: always()
        with:
          name: pvs-report
          path: pvs-report.html
