name: PVS-Studio Static Analysis

on: workflow_dispatch

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v6.0.2

      - name: Set Up .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Install PVS-Studio
        run: |
          wget -q -O - https://wcdn.pvs-studio.com/etc/pubkey.txt | sudo apt-key add -
          sudo wget -O /etc/apt/sources.list.d/viva64.list https://wcdn.pvs-studio.com/etc/viva64.list
          sudo apt-get update
          sudo apt-get install pvs-studio-dotnet

      - name: Set PVS-Studio License
        run: pvs-studio-analyzer credentials ${{secrets.PVS_NAME}} ${{secrets.PVS_KEY}}

      - name: Run PVS-Studio Analysis
        run: |
          pvs-studio-dotnet analyze -t "Bank/Bank.sln" -o "BankLog.plog"
      
      - name: Convert Report to Readable Format
        run: |
          plog-converter \
            -a GA:1,2 \
            -t fullhtml \
            -o pvs-report.html \
            pvs-report.json

      - name: Artifact PVS Report
        uses: actions/upload-artifact@v5.0.0
        if: always()
        with:
          name: pvs-report
          path: pvs-report.html
